### ISSUE TITLE
Raspberry Pi doesn't initialise

### ISSUE THREAD

**Issue by ollietb** [rlamarche/camera-toolbox-images#1]
I followed the instructions and used Win32DiskImager to write the .img file to the RPi SD card. When I turn on the RPi device with ethernet, keyboard and camera plugged in I get some set up feedback but it doesn't initialise the desktop to show the live feed. I can connect to the 'camera' WiFi network but the IP 172.24.1.1 is not responding.

![img_5739](https://cloud.githubusercontent.com/assets/342090/22471423/2f44f40c-e7ca-11e6-9248-df4f1d7c6ef0.JPG)

**Comment by ollietb** [comment]
This is on a Raspberry Pi 3 - Model B

**Comment by ollietb** [comment]
![img_5740](https://cloud.githubusercontent.com/assets/342090/22472438/8cca6fd2-e7cd-11e6-8a29-e1389b33c756.JPG)

![img_5741](https://cloud.githubusercontent.com/assets/342090/22472449/91a59130-e7cd-11e6-9e7d-b2684da6b4ac.JPG)

**Comment by rlamarche** [comment]
Hi,

It seems that the camera-toolbox binary is not working.
The image is not up to date and I fixed some errors on the master.

I see that you are using a Canon EOS700D.
In the last version I have added fix for using canon cameras.

If you want I can send you the last binary.

The best option would be to add a auto-update process but you would need to connect the RPI to your local network with internet. This feature should not be complicated to develop and would make easier the update process.

For now, unzip this file in /usr/local/bin to override the old version with the new one and restart :
[camera-toolbox.zip](https://github.com/rlamarche/camera-toolbox-images/files/753167/camera-toolbox.zip)

**Comment by foxinsox** [comment]
Hey,
i wanted to check out this amazing project with my canon eos 700D, but unfortunately also I didn't succeed.
The Raspberry Pi 3, Model B doesn't fully initialize.. Please refer to the added Screenshots for the full console log.
It sets up the WiFi and I can connect to it and ping it under 172.24.1.1, however any attempt to access it via ssh fails (saying that password "camera" is incorrect). Also in the console of RaspberryPi itself it seems like he doesn't accept the root password "camera".
Unfortunately, due to that, I can't exchange the binary in /usr/local/bin…
Any help would be highly appreciated! 
![img_2650](https://cloud.githubusercontent.com/assets/8191065/23264375/689c1a9a-f9e1-11e6-8a33-b614ce007a6b.JPG)

Merci bien! :)

**Comment by rlamarche** [comment]
Can you show me the command you use to connect ?
I'm very surprised that the password `camera` does not work.

The good command would be :

```
ssh root@172.24.1.1
```

As seen here : https://github.com/rlamarche/camera-toolbox-buildroot/blob/master/rpi3_cameratoolbox_config#L354 , the password should be `camera` but it is possible that I changed it before commit.
Try with `cameratoolbox" ? or "buildroot" ?

If nothing work, I'll build a new image with up-to-date camera-toolbox binary.

**Comment by foxinsox** [comment]
Hey,
that was absolutely stupid of me, thanks for your very quick reply!! The mistake was that I always tried to connect to `ssh cameratoolbox@172.24.1.1` . Now I can ssh-connect to it and I just exchanged the camera-toolbox binary. But now i'm still having the same problem: The same console screen as on the image i attached before, and i can ping the cameratoolbox, but anything like calling `172.24.1.1:8080/api/v1/status` fails with no connection.
I attached the Canon Eos 700D via usb and turned on in Movie-Capture mode.

**Comment by rlamarche** [comment]
ok can you try to start manually camera-toolbox in /usr/local/bin/camera-toolbox ? (kill it before if necessary).

Please paste here the output.

At the moment, I know that I've a lot of work to support Canon Cameras because widgets names & behaviour differs form Nikon Cameras.

**Comment by ollietb** [comment]
@rlamarche here is my output
```
# /usr/local/bin/camera-toolbox
Unable to query physical screen size, defaulting to 100 dpi.
To override, set QT_QPA_EGLFS_PHYSICAL_WIDTH and QT_QPA_EGLFS_PHYSICAL_HEIGHT (in millimeters).
1 cameras detected.
Open camera : "Canon EOS 70D" at port "usb:001,005"
Error : "Unable to get single config shootingmode: Bad parameters"
Error : "Unable to get single config exposurecompensation: Bad parameters"
Start camera thread
Start liveview decoder thread
Idle event: Unknown
Unknown data: PTP Property d105 changed
Error : "Unable to get single config shootingmode: Bad parameters"
Error : "Unable to get single config exposurecompensation: Bad parameters"
Idle event: Unknown
Unknown data: PTP Property d108 changed
Error : "Unable to get single config shootingmode: Bad parameters"
Error : "Unable to get single config exposurecompensation: Bad parameters"
Idle event: Unknown
Unknown data: PTP Property d106 changed
Error : "Unable to get single config shootingmode: Bad parameters"
Error : "Unable to get single config exposurecompensation: Bad parameters"
Idle event: Unknown
Unknown data: PTP Property d107 changed
Error : "Unable to get single config shootingmode: Bad parameters"
Error : "Unable to get single config exposurecompensation: Bad parameters"
Idle event: Unknown
Unknown data: PTP Property d109 changed
Error : "Unable to get single config shootingmode: Bad parameters"
Error : "Unable to get single config exposurecompensation: Bad parameters"
Idle event: Unknown
Unknown data: PTP Property d10a changed
Error : "Unable to get single config shootingmode: Bad parameters"
Error : "Unable to get single config exposurecompensation: Bad parameters"
Idle event: Unknown
Unknown data: PTP Property d10b changed
Error : "Unable to get single config shootingmode: Bad parameters"
Error : "Unable to get single config exposurecompensation: Bad parameters"
Idle event: Unknown
Unknown data: PTP Property d10c changed
Error : "Unable to get single config shootingmode: Bad parameters"
Error : "Unable to get single config exposurecompensation: Bad parameters"
Idle event: Unknown
Unknown data: PTP Property d10d changed
Error : "Unable to get single config shootingmode: Bad parameters"
Error : "Unable to get single config exposurecompensation: Bad parameters"
Idle event: Unknown
Unknown data: PTP Property d10e changed
Error : "Unable to get single config shootingmode: Bad parameters"
Error : "Unable to get single config exposurecompensation: Bad parameters"
Idle event: Unknown
Unknown data: PTP Property d10f changed
Error : "Unable to get single config shootingmode: Bad parameters"
Error : "Unable to get single config exposurecompensation: Bad parameters"
Idle event: Unknown
Unknown data: PTP Property d11b changed
Error : "Unable to get single config shootingmode: Bad parameters"
Error : "Unable to get single config exposurecompensation: Bad parameters"
```
and it was going on...

**Comment by ollietb** [comment]
Ok I managed to get it working by restarting with everything plugged in. The live preview is empty though

**Comment by ollietb** [comment]
![img_5870](https://cloud.githubusercontent.com/assets/342090/23269239/cfd698ba-f9e7-11e6-976b-5e6b8bf362ea.JPG)

This is the result from 172.24.1.1:8080/api/v1/status
{
"aperture": "5.6",
"apertures": [
"5.6",
"6.3",
"7.1",
"8",
"9",
"10",
"11",
"13",
"14",
"16",
"18",
"20",
"22",
"25",
"29",
"32",
"36"
],
"captureMode": 0,
"exposureMode": "",
"exposureModes": [],
"focusMetering": "",
"focusMeterings": [],
"focusMode": "One Shot",
"focusModes": [
"One Shot",
"AI Focus",
"AI Servo"
],
"isInLiveView": false,
"isRecording": false,
"iso": "1250",
"isoAuto": true,
"isos": [
"Auto",
"100",
"125",
"160",
"200",
"250",
"320",
"400",
"500",
"640",
"800",
"1000",
"1250",
"1600",
"2000",
"2500",
"3200",
"4000",
"5000",
"6400",
"8000",
"10000",
"12800"
],
"shutterSpeed": "1/60",
"shutterSpeeds": [
"30",
"25",
"20",
"15",
"13",
"10",
"8",
"6",
"5",
"4",
"3.2",
"2.5",
"2",
"1.6",
"1.3",
"1",
"0.8",
"0.6",
"0.5",
"0.4",
"0.3",
"1/4",
"1/5",
"1/6",
"1/8",
"1/10",
"1/13",
"1/15",
"1/20",
"1/25",
"1/30",
"1/40",
"1/50",
"1/60",
"1/80",
"1/100",
"1/125",
"1/160",
"1/200",
"1/250",
"1/320",
"1/400",
"1/500",
"1/640",
"1/800",
"1/1000",
"1/1250",
"1/1600",
"1/2000",
"1/2500",
"1/3200",
"1/4000",
"1/5000",
"1/6400",
"1/8000"
]
}

**Comment by rlamarche** [comment]
ok it seems to be like https://github.com/rlamarche/camera-toolbox/issues/4

Please run : gphoto2 --list-all-config 
And join the results on the issue.

**Comment by foxinsox** [comment]
Unfortunately nothing happens when i run it. Also when I'm listing all the processes, i can neither find it there after restart or after running ./camera-toolbox …
```
# cd usr/local/bin/
# ps -a
PID   USER     COMMAND
    1 root     init
    2 root     [kthreadd]
    3 root     [ksoftirqd/0]
    4 root     [kworker/0:0]
    5 root     [kworker/0:0H]
    6 root     [kworker/u8:0]
    7 root     [rcu_sched]
    8 root     [rcu_bh]
    9 root     [migration/0]
   10 root     [migration/1]
   11 root     [ksoftirqd/1]
   12 root     [kworker/1:0]
   13 root     [kworker/1:0H]
   14 root     [migration/2]
   15 root     [ksoftirqd/2]
   16 root     [kworker/2:0]
   17 root     [kworker/2:0H]
   18 root     [migration/3]
   19 root     [ksoftirqd/3]
   20 root     [kworker/3:0]
   21 root     [kworker/3:0H]
   22 root     [kdevtmpfs]
   23 root     [netns]
   24 root     [perf]
   25 root     [khungtaskd]
   26 root     [writeback]
   27 root     [crypto]
   28 root     [bioset]
   29 root     [kblockd]
   30 root     [kworker/0:1]
   31 root     [rpciod]
   32 root     [kswapd0]
   33 root     [vmstat]
   34 root     [fsnotify_mark]
   35 root     [nfsiod]
   44 root     [kthrotld]
   45 root     [kworker/1:1]
   46 root     [bioset]
   47 root     [bioset]
   48 root     [bioset]
   49 root     [bioset]
   50 root     [bioset]
   51 root     [bioset]
   52 root     [bioset]
   53 root     [bioset]
   54 root     [bioset]
   55 root     [bioset]
   56 root     [bioset]
   57 root     [bioset]
   58 root     [bioset]
   59 root     [bioset]
   60 root     [bioset]
   61 root     [bioset]
   62 root     [bioset]
   63 root     [bioset]
   64 root     [bioset]
   65 root     [bioset]
   66 root     [bioset]
   67 root     [bioset]
   68 root     [bioset]
   69 root     [bioset]
   70 root     [VCHIQ-0]
   71 root     [VCHIQr-0]
   72 root     [VCHIQs-0]
   73 root     [iscsi_eh]
   74 root     [dwc_otg]
   75 root     [kworker/3:1]
   76 root     [DWC Notificatio]
   77 root     [kworker/u8:1]
   78 root     [irq/92-mmc1]
   79 root     [bioset]
   80 root     [mmcqd/0]
   81 root     [kworker/2:1]
   82 root     [VCHIQka-0]
   83 root     [SMIO]
   84 root     [deferwq]
   85 root     [kworker/u8:2]
   86 root     [kworker/3:2]
   87 root     [kworker/2:1H]
   88 root     [jbd2/mmcblk0p2-]
   89 root     [ext4-rsv-conver]
   90 root     [kworker/3:1H]
   91 root     [kworker/0:1H]
  102 root     /sbin/syslogd -n
  105 root     /sbin/klogd -n
  108 root     /sbin/udevd -d
  110 root     [kworker/1:1H]
  129 root     [cfg80211]
  130 root     [brcmf_wq/mmc1:0]
  131 root     [brcmf_wdog/mmc1]
  132 root     [kworker/2:2]
  144 dbus     dbus-daemon --system
  155 root     [ipv6_addrconf]
  188 root     [kworker/2:3]
  194 root     /usr/sbin/sshd
  199 nobody   /usr/sbin/dnsmasq
  203 root     /usr/sbin/hostapd /etc/hostapd.conf
  208 root     /sbin/getty -L console 0 vt100
  210 root     -sh
  211 root     [kworker/0:2]
  221 root     sshd: root@pts/0
  223 root     -sh
  226 root     [kworker/u8:3]
  227 root     [kworker/u8:4]
  230 root     ps ?-a
# ./camera-toolbox 
# QT_QPA_EGLFS_FORCE888=1 ./camera-toolbox
# 
```
PS: should i open another issue for that?

**Comment by rlamarche** [comment]
yes please open a ticket on https://github.com/rlamarche/camera-toolbox/issues/ on the same pattern as this ticket https://github.com/rlamarche/camera-toolbox/issues/4

Leave this ticket open because I need to update the image and provide a binary auto-update feature.

**Comment by rlamarche** [comment]
@foxinsox Have you tried to activate liveview with the key ENTER from the KEYPAD ?

**Comment by foxinsox** [comment]
Yes I just tried that, but if i press any key – no matter which one – , he just says
```
Welcome to Camera Toolbox
cameratoolbox login:
```
and gives me the possibility to login as root. But no liveview. Opening new ticket now as you suggested.

**Comment by rlamarche** [comment]
try by running camera-toolbox manually (kill the existing process and unplug / restart your camera)

**Comment by foxinsox** [comment]
Same as before… nothing happens when i run it. Also when I'm listing all the processes, i can neither find it there after restart nor after running either  `./camera-toolbox` or `QT_QPA_EGLFS_FORCE888=1 ./camera-toolbox`

List of processes: 
```
# cd usr/local/bin/
# ps -a
PID   USER     COMMAND
    1 root     init
    2 root     [kthreadd]
    3 root     [ksoftirqd/0]
    4 root     [kworker/0:0]
    5 root     [kworker/0:0H]
    6 root     [kworker/u8:0]
    7 root     [rcu_sched]
    8 root     [rcu_bh]
    9 root     [migration/0]
   10 root     [migration/1]
   11 root     [ksoftirqd/1]
   12 root     [kworker/1:0]
   13 root     [kworker/1:0H]
   14 root     [migration/2]
   15 root     [ksoftirqd/2]
   16 root     [kworker/2:0]
   17 root     [kworker/2:0H]
   18 root     [migration/3]
   19 root     [ksoftirqd/3]
   20 root     [kworker/3:0]
   21 root     [kworker/3:0H]
   22 root     [kdevtmpfs]
   23 root     [netns]
   24 root     [perf]
   25 root     [khungtaskd]
   26 root     [writeback]
   27 root     [crypto]
   28 root     [bioset]
   29 root     [kblockd]
   30 root     [kworker/0:1]
   31 root     [rpciod]
   32 root     [kswapd0]
   33 root     [vmstat]
   34 root     [fsnotify_mark]
   35 root     [nfsiod]
   44 root     [kthrotld]
   45 root     [kworker/1:1]
   46 root     [bioset]
   47 root     [bioset]
   48 root     [bioset]
   49 root     [bioset]
   50 root     [bioset]
   51 root     [bioset]
   52 root     [bioset]
   53 root     [bioset]
   54 root     [bioset]
   55 root     [bioset]
   56 root     [bioset]
   57 root     [bioset]
   58 root     [bioset]
   59 root     [bioset]
   60 root     [bioset]
   61 root     [bioset]
   62 root     [bioset]
   63 root     [bioset]
   64 root     [bioset]
   65 root     [bioset]
   66 root     [bioset]
   67 root     [bioset]
   68 root     [bioset]
   69 root     [bioset]
   70 root     [VCHIQ-0]
   71 root     [VCHIQr-0]
   72 root     [VCHIQs-0]
   73 root     [iscsi_eh]
   74 root     [dwc_otg]
   75 root     [kworker/3:1]
   76 root     [DWC Notificatio]
   77 root     [kworker/u8:1]
   78 root     [irq/92-mmc1]
   79 root     [bioset]
   80 root     [mmcqd/0]
   81 root     [kworker/2:1]
   82 root     [VCHIQka-0]
   83 root     [SMIO]
   84 root     [deferwq]
   85 root     [kworker/u8:2]
   86 root     [kworker/3:2]
   87 root     [kworker/2:1H]
   88 root     [jbd2/mmcblk0p2-]
   89 root     [ext4-rsv-conver]
   90 root     [kworker/3:1H]
   91 root     [kworker/0:1H]
  102 root     /sbin/syslogd -n
  105 root     /sbin/klogd -n
  108 root     /sbin/udevd -d
  110 root     [kworker/1:1H]
  129 root     [cfg80211]
  130 root     [brcmf_wq/mmc1:0]
  131 root     [brcmf_wdog/mmc1]
  132 root     [kworker/2:2]
  144 dbus     dbus-daemon --system
  155 root     [ipv6_addrconf]
  188 root     [kworker/2:3]
  194 root     /usr/sbin/sshd
  199 nobody   /usr/sbin/dnsmasq
  203 root     /usr/sbin/hostapd /etc/hostapd.conf
  208 root     /sbin/getty -L console 0 vt100
  210 root     -sh
  211 root     [kworker/0:2]
  221 root     sshd: root@pts/0
  223 root     -sh
  226 root     [kworker/u8:3]
  227 root     [kworker/u8:4]
  230 root     ps ?-a
# ./camera-toolbox 
# QT_QPA_EGLFS_FORCE888=1 ./camera-toolbox
# 
```

**Comment by rlamarche** [comment]
On this comment https://github.com/rlamarche/camera-toolbox-images/issues/1#issuecomment-282049669 you managed to have camera-toolbox working. How did you do ?

**Comment by foxinsox** [comment]
I'm afraid you're mixing up @ollietb with @foxinsox … i never made it run. sorry for hijacking this issue. I opened up a new one [here](https://github.com/rlamarche/camera-toolbox/issues/5).

**Comment by rlamarche** [comment]
Indeed ! I'm sorry :joy:

**Comment by rlamarche** [comment]
@ollietb when running, use the ENTER (or RETURN) from KEYPAD to activate liveview.
